version: '2.1'
orbs:
  datadog-static-analysis: juli1/rosie-orb@dev:alpha
jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - datadog-static-analysis/analyze:
          DD_APP_KEY: $DD_APP_KEY
          DD_API_KEY: $DD_API_KEY
          DD_ENV: $DD_ENV
          DD_SERVICE: $DD_SERVICE
          DD_SITE: $DD_SITE
workflows:
  main:
    jobs:
      - build:
          context: datadog-static-analysis
